DELETE http://localhost:3003/api/blogs/63e458b1ff5143cd84fd7b11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjNlNDU4OTJmZjUxNDNjZDg0ZmQ3YjA3IiwiaWF0IjoxNjc1OTA5Mjc3LCJleHAiOjE2NzU5MTI4Nzd9.izC8AEjDc71KewoaLTn174kiG60Mpao4WD6n6N0_PF0