POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhZFVzZXIiLCJpZCI6IjYzZTFmYTBkYTU2NzIyYjA5N2ZlYWY0MiIsImlhdCI6MTY3NTc1NDAyNCwiZXhwIjoxNjc1NzU3NjI0fQ.MjZzG4HuoJLH7DOQ6-zqwTfRXYgNwfgZhyC56ELRn4Y

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes": 0
}