POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhZFVzZXIiLCJpZCI6IjYzZTQ0Zjk0YjgxNjhhNjkwNmQ5NzRkYyIsImlhdCI6MTY3NTkwNjk4MCwiZXhwIjoxNjc1OTEwNTgwfQ.qMYcwzuBB9RkDttoA35jPbSfCckukqRGPiaiIVHENz4

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes": 0
}